server:
  port: 8081
 
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://dpg-d8f0u76q1p3s73de3ud0-a.virginia-postgres.render.com:5432/ttrpgmanager?sslmode=require
    username: ttrpgmanager_user
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
 
  jpa:
    hibernate:
      ddl-auto: create-drop
 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql